spring:
  profiles:
    active: dev
wechat:
  appId: wx1353e9f7ea1773cd
  appSecret: 0dab0527b9bf519a3b76aff62fdd9524
huaweicloud:
  ak: ${HUAWEICLOUD_AK}
  sk: ${HUAWEICLOUD_SK}
  #如果是上海一，请填写"cn-east-3"；如果是北京四，请填写"cn-north-4";
  regionId: cn-south-1
  endpoint: 3353be6ef0.st1.iotda-app.cn-south-1.myhuaweicloud.com
  projectId: 0c6d4e22c680f3ae2f8dc001e54403fb
  #amqp相关配置 第二天课程接收设备数据使用
  host: 3353be6ef0.st1.iotda-app.cn-south-1.myhuaweicloud.com
  accessKey: Vl8yf0Z7
  accessCode: yqsHnMDrnD2YBybrNdEkZ6cN1rDofn1o
  queueName: DefaultQueue   #默认无需改动
# 数据告警配置
alert:
  deviceMaintainerRole: 维修工
  managerRole: 超级管理员